apiVersion: v1
kind: Namespace
metadata:
  name: student-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: student-api-sa
  namespace: student-app
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: student-api-role
  namespace: student-app
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: student-api-rb
  namespace: student-app
subjects:
  - kind: ServiceAccount
    name: student-api-sa
    namespace: student-app
roleRef:
  kind: Role
  name: student-api-role
  apiGroup: rbac.authorization.k8s.io